#!/usr/bin/env python3
"""Prepare MadGraph input decks from the diphoton priority points.

This is the MadGraph *basis*: it turns each 2HDMC diphoton priority point into a
renderable MadGraph input deck (process / run / param card fragments plus a
documented run command) and emits a normalized run-table *skeleton* that a real
MadGraph run must fill in.

It deliberately does not:

* ship or generate a UFO/model,
* install or run MadGraph, or
* invent any cross section.

Every skeleton row leaves the cross-section fields blank.  Once a real MadGraph
run exists, copy the filled skeleton to ``data/manual/madgraph_xsec_runs.csv`` and
feed it to ``scripts/11_ingest_madgraph_xsec.py`` (``make madgraph-sigma``).
"""
from __future__ import annotations

import argparse
import stat
from pathlib import Path

import pandas as pd

from llp_recast.madgraph import (
    DEFAULT_PROCESS,
    DEFAULT_SQRT_S_TEV,
    MODEL_PLACEHOLDER,
    TEMPLATE_DIR,
    build_run_skeleton,
    deck_context,
    render_template,
)

DEFAULT_PRIORITY = Path("outputs/diphoton_2hdmc_bridge/priority_points_for_sigma.csv")
DEFAULT_DECK_ROOT = Path("outputs/madgraph_runs")
DEFAULT_SKELETON = DEFAULT_DECK_ROOT / "madgraph_xsec_runs_skeleton.csv"

# template filename -> rendered filename inside each per-point deck directory
DECK_FILES = {
    "proc_card.dat.tmpl": "proc_card.dat",
    "run_card_fragment.dat.tmpl": "run_card_fragment.dat",
    "param_card_fragment.dat.tmpl": "param_card_fragment.dat",
    "run_commands.sh.tmpl": "run_commands.sh",
}

NON_EXCLUSION_FLAG = "NOT_EXCLUSION_ACCEPTANCE_AND_SIGNAL_MODEL_REQUIRED"


def read_csv_or_empty(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def load_templates(template_dir: Path) -> dict[str, str]:
    if not template_dir.exists():
        raise FileNotFoundError(
            f"MadGraph template directory not found: {template_dir} "
            "(expected the committed basis under data/madgraph/templates)"
        )
    templates: dict[str, str] = {}
    for name in DECK_FILES:
        path = template_dir / name
        if not path.exists():
            raise FileNotFoundError(f"missing MadGraph deck template: {path}")
        templates[name] = path.read_text(encoding="utf-8")
    return templates


def render_decks(
    priority: pd.DataFrame,
    skeleton: pd.DataFrame,
    templates: dict[str, str],
    *,
    deck_root: Path,
    model_name: str,
) -> list[Path]:
    """Render one input deck per skeleton row.  Returns the deck directories."""
    written: list[Path] = []
    if skeleton.empty:
        return written
    for _, row in skeleton.iterrows():
        run_dir = deck_root / str(row["mg_run_name"])
        run_dir.mkdir(parents=True, exist_ok=True)
        mapping = deck_context(row, model_name=model_name)
        for template_name, out_name in DECK_FILES.items():
            rendered = render_template(templates[template_name], mapping)
            out_path = run_dir / out_name
            out_path.write_text(rendered, encoding="utf-8")
            if out_name.endswith(".sh"):
                out_path.chmod(out_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(run_dir)
    return written


def write_readme(deck_root: Path, *, priority: pd.DataFrame, skeleton: pd.DataFrame, skeleton_path: Path, model_name: str) -> Path:
    path = deck_root / "README.md"
    text = f"""# MadGraph run preparation

Generated by `scripts/12_prepare_madgraph_runs.py`.

## Purpose

This is the MadGraph *basis*.  For each 2HDMC diphoton priority point it renders a
MadGraph input deck and records one row of a normalized run-table skeleton.  No
UFO/model is shipped, MadGraph is not installed or run, and no cross section is
invented — every skeleton cross-section field is blank on purpose.

## Counts

- Priority points loaded: {len(priority)}
- Decks prepared: {len(skeleton)}
- Model placeholder: `{model_name}`

## Outputs

- `madgraph_xsec_runs_skeleton.csv`: normalized run-table skeleton (blank cross sections).
- `<run_tag>/proc_card.dat`, `run_card_fragment.dat`, `param_card_fragment.dat`,
  `run_commands.sh`: per-point input deck.

## Next steps

1. Supply a real UFO/model in place of `{model_name}`.
2. Run MadGraph with each `<run_tag>/proc_card.dat` (see `run_commands.sh`).
3. Record each run's cross section (pb or fb) in the skeleton, then copy it to
   `data/manual/madgraph_xsec_runs.csv` and run `make madgraph-sigma`.

## Non-exclusion policy

Downstream ratios remain `{NON_EXCLUSION_FLAG}`.  Preparing decks is not an
exclusion and does not by itself produce any physical result.
"""
    path.write_text(text, encoding="utf-8")
    return path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare MadGraph input decks from diphoton priority points")
    parser.add_argument("--priority", type=Path, default=DEFAULT_PRIORITY)
    parser.add_argument("--template-dir", type=Path, default=TEMPLATE_DIR)
    parser.add_argument("--deck-root", type=Path, default=DEFAULT_DECK_ROOT)
    parser.add_argument("--skeleton-out", type=Path, default=DEFAULT_SKELETON)
    parser.add_argument("--max-rows", type=int, default=50)
    parser.add_argument("--process", type=str, default=DEFAULT_PROCESS)
    parser.add_argument("--sqrt-s-tev", type=float, default=DEFAULT_SQRT_S_TEV)
    parser.add_argument("--model-name", type=str, default=MODEL_PLACEHOLDER)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.deck_root.mkdir(parents=True, exist_ok=True)

    priority = read_csv_or_empty(args.priority)
    templates = load_templates(args.template_dir)

    skeleton = build_run_skeleton(
        priority,
        max_rows=args.max_rows,
        process=args.process,
        sqrt_s_TeV=args.sqrt_s_tev,
        model_name=args.model_name,
        deck_root=args.deck_root,
    )
    args.skeleton_out.parent.mkdir(parents=True, exist_ok=True)
    skeleton.to_csv(args.skeleton_out, index=False)

    decks = render_decks(priority, skeleton, templates, deck_root=args.deck_root, model_name=args.model_name)
    write_readme(args.deck_root, priority=priority, skeleton=skeleton, skeleton_path=args.skeleton_out, model_name=args.model_name)

    print(f"[OK] wrote run-table skeleton under {args.skeleton_out}")
    print(f"[OK] priority points loaded: {len(priority)}")
    print(f"[OK] decks prepared: {len(decks)}")
    print(f"[OK] model placeholder: {args.model_name}")
    print("[OK] no cross section fabricated; skeleton cross-section fields are blank")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
